import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { CarteiraComponent } from './carteira';

describe('CarteiraComponent', () => {
  let fixture: ComponentFixture<CarteiraComponent>; let http: HttpTestingController;
  beforeEach(async () => { await TestBed.configureTestingModule({ imports: [CarteiraComponent], providers: [provideRouter([]), provideHttpClient(), provideHttpClientTesting()] }).compileComponents(); fixture = TestBed.createComponent(CarteiraComponent); http = TestBed.inject(HttpTestingController); });
  afterEach(() => http.verify());
  function start(items: any[] = []): void { fixture.detectChanges(); http.expectOne('/api/corretoras').flush([]); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items, page: 0, size: 20, totalElements: items.length, totalPages: items.length ? 1 : 0 }); fixture.detectChanges(); }

  it('reserva skeleton inicial e apresenta vazio confirmado', () => { fixture.detectChanges(); http.expectOne('/api/corretoras').flush([]); expect(fixture.nativeElement.querySelector('[aria-busy="true"]')).toBeTruthy(); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Nenhuma posição aberta encontrada'); });
  it('renderiza cartão com nome, corretora e métricas financeiras exatas do read model', () => { start([position(1, 'PETR4', 'Corretora Atlas', 2, 'BRL')]); const root = fixture.nativeElement as HTMLElement; const text = root.textContent; expect(root.querySelector('.position-card')).toBeTruthy(); expect(text).toContain('Petróleo Brasileiro S.A.'); expect(text).toContain('Corretora Atlas'); expect(text).toContain('R$ 10,50'); expect(text).toContain('R$ 21,00'); expect(text).toContain('R$ 12,00'); expect(text).toContain('R$ 24,00'); expect(text).toContain('R$ 3,00'); expect(text).toContain('14,29%'); expect(text).toContain('R$ 4,00'); expect(text).toContain('Preço médio'); expect(text).toContain('Inclui custos das compras'); expect(text).toContain('Resultado realizado'); expect(text).not.toContain('ledger'); });
  it('mantém as cinco métricas e o rodapé financeiro visíveis no cartão compacto', () => { start([position(1, 'PETR4', 'Corretora Atlas', 2, 'BRL')]); const card = (fixture.nativeElement as HTMLElement).querySelector('.position-card') as HTMLElement; expect(card.querySelectorAll('.primary-metrics > div')).toHaveLength(5); expect(card.textContent).toContain('Quantidade'); expect(card.textContent).toContain('Preço médio'); expect(card.textContent).toContain('Cotação atual'); expect(card.textContent).toContain('Valor atual'); expect(card.textContent).toContain('Resultado não realizado'); expect(card.textContent).toContain('Custo da posição'); expect(card.textContent).toContain('Resultado realizado'); });
  it('mantém o mesmo ticker separado por corretora e grupo de posição', () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL'), position(2, 'PETR4', 'Corretora B', 3, 'BRL')]); expect(fixture.componentInstance.visiblePositions).toHaveLength(2); fixture.detectChanges(); expect(fixture.nativeElement.querySelectorAll('[data-position-id]').length).toBeGreaterThanOrEqual(2); expect(fixture.nativeElement.textContent).toContain('Corretora A'); expect(fixture.nativeElement.textContent).toContain('Corretora B'); });
  it('apresenta BRL e USD sem patrimônio consolidado entre moedas', () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL'), position(2, 'AAPL', 'Corretora B', 1, 'USD')]); const text = fixture.nativeElement.textContent; expect(text).toContain('R$ 24,00'); expect(text).toContain('US$ 24,00'); expect(text).not.toContain('Patrimônio consolidado'); expect(fixture.componentInstance.visiblePositions.map(item => item.nativeCurrency)).toEqual(['USD', 'BRL']); });
  it('mostra métricas indisponíveis sem criar zero financeiro', () => { const item = position(1, 'AAPL', 'Corretora A', 1, 'USD'); item.currentQuote = unavailable('USD'); item.marketValue = unavailable('USD'); item.unrealizedResult = unavailable('USD'); item.unrealizedResultPercentage = { availability: 'UNAVAILABLE', value: null, reason: 'QUOTE_UNAVAILABLE' }; start([item]); const text = fixture.nativeElement.textContent; expect(text).toContain('Indisponível'); expect(text).not.toContain('US$ 0,00'); });
  it('mantém valor stale visível com aviso compacto de cotação desatualizada', () => { const item = position(1, 'PETR4', 'Corretora A', 1, 'BRL'); item.currentQuote = { ...item.currentQuote, availability: 'STALE' }; item.marketValue = { ...item.marketValue, availability: 'STALE' }; item.quoteProvenance = { ...item.quoteProvenance, availability: 'STALE' }; start([item]); const text = fixture.nativeElement.textContent; expect(text).toContain('R$ 12,00'); expect(text).toContain('Cotação desatualizada'); });
  it('mostra ganho, perda e sem variação sem rótulos duplicados', () => { const gain = position(1, 'PETR4', 'Corretora A', 1, 'BRL'); const loss = position(2, 'VALE3', 'Corretora B', 1, 'BRL'); const flat = position(3, 'ITUB4', 'Corretora C', 1, 'BRL'); loss.unrealizedResult = { ...loss.unrealizedResult, value: -2 }; loss.unrealizedResultPercentage = { ...loss.unrealizedResultPercentage, value: -8 }; flat.unrealizedResult = { ...flat.unrealizedResult, value: 0 }; flat.unrealizedResultPercentage = { ...flat.unrealizedResultPercentage, value: 0 }; start([gain, loss, flat]); const text = fixture.nativeElement.textContent; expect(text).toContain('Ganho'); expect(text).toContain('Perda'); expect(text).toContain('Sem variação'); expect(text).not.toContain('Neutro: Resultado'); });
  it('mantém corretora longa acessível em uma lista direta de cartões', () => { const broker = 'Corretora com nome muito longo para conferir a estrutura'; start([position(1, 'PETR4', broker, 1, 'BRL'), position(2, 'PETR4', 'Corretora B', 1, 'BRL')]); const root = fixture.nativeElement as HTMLElement; expect(root.querySelectorAll('.position-grid .position-card')).toHaveLength(2); expect(root.querySelector('.broker-name')?.getAttribute('title')).toBe(broker); expect(root.querySelector('.position-grid')).toBeTruthy(); expect(root.querySelector('app-responsive-data-list')).toBeNull(); });
  it('não exibe posição encerrada quando ela não integra as posições abertas do backend', () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL')]); expect(fixture.nativeElement.textContent).toContain('PETR4'); expect(fixture.nativeElement.textContent).not.toContain('CLOSED3'); });
  it('envia filtros server-side e mantém busca/ordenação local', () => { start([position(1, 'PETR4', 'Corretora B', 2, 'BRL'), position(2, 'PETR4', 'Corretora A', 5, 'BRL')]); const component = fixture.componentInstance; component.filters.setValue({ search: 'corretora', market: 'BRASIL', brokerId: 7, sort: 'broker' }); component.applyFilters(); const request = http.expectOne(value => value.url === '/api/carteira/posicoes/detalhadas'); expect(request.request.params.get('market')).toBe('BRASIL'); expect(request.request.params.get('brokerId')).toBe('7'); request.flush({ items: [position(1, 'PETR4', 'Corretora B', 2, 'BRL'), position(2, 'PETR4', 'Corretora A', 5, 'BRL')], page: 0, size: 20, totalElements: 2, totalPages: 1 }); expect(component.visiblePositions.map(item => item.brokerName)).toEqual(['Corretora A', 'Corretora B']); });
  it('preserva dados anteriores durante refresh e atualiza o DOM zoneless quando a resposta chega', () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL')]); const component = fixture.componentInstance; component.load(); expect(component.visiblePositions[0].ticker).toBe('PETR4'); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('PETR4'); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items: [position(2, 'VALE3', 'Corretora B', 3, 'BRL')], page: 0, size: 20, totalElements: 1, totalPages: 1 }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('VALE3'); });
  it('preserva posição e mostra stale em falha posterior', () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL')]); fixture.componentInstance.load(); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({}, { status: 503, statusText: 'Unavailable' }); expect(fixture.componentInstance.facade.state().status).toBe('stale'); expect(fixture.componentInstance.visiblePositions).toHaveLength(1); });
  it('mantém a carga inicial somente leitura, sem PUT de cotação', () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL')]); http.expectNone(request => request.method === 'PUT' && request.url.includes('/atualizar-cotacao')); });
  it('renova ativo distinto uma vez antes de reler posições com filtros e paginação atuais', () => { const items = [position(1, 'PETR4', 'Corretora A', 2, 'BRL'), { ...position(2, 'PETR4', 'Corretora B', 3, 'BRL'), assetId: 1 }]; start(items); const component = fixture.componentInstance; component.page = 1; component.filters.setValue({ search: 'petr4', market: 'BRASIL', brokerId: 7, sort: 'broker' }); component.refreshQuotes(); http.expectOne('/api/acoes/1/atualizar-cotacao').flush({}); const read = http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas'); expect(read.request.params.get('page')).toBe('1'); expect(read.request.params.get('market')).toBe('BRASIL'); expect(read.request.params.get('brokerId')).toBe('7'); expect(component.filters.controls.sort.value).toBe('broker'); read.flush({ items, page: 1, size: 20, totalElements: 2, totalPages: 2 }); });
  it('preserva posições e relê após falha parcial de renovação', () => { const items = [position(1, 'PETR4', 'Corretora A', 2, 'BRL'), position(2, 'AAPL', 'Corretora B', 1, 'USD')]; start(items); fixture.componentInstance.refreshQuotes(); http.expectOne('/api/acoes/1/atualizar-cotacao').flush({}, { status: 503, statusText: 'Unavailable' }); http.expectOne('/api/acoes/2/atualizar-cotacao').flush({}); expect(fixture.componentInstance.visiblePositions).toHaveLength(2); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items, page: 0, size: 20, totalElements: 2, totalPages: 1 }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Algumas cotações não puderam ser atualizadas'); });
  it('encerra timeout de renovação e permite nova tentativa', async () => { start([position(1, 'PETR4', 'Corretora A', 2, 'BRL')]); fixture.componentInstance.quoteRefreshTimeoutMs = 1; fixture.componentInstance.refreshQuotes(); http.expectOne('/api/acoes/1/atualizar-cotacao'); await new Promise(resolve => setTimeout(resolve, 15)); expect(fixture.componentInstance.refreshingQuotes).toBe(false); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items: [position(1, 'PETR4', 'Corretora A', 2, 'BRL')], page: 0, size: 20, totalElements: 1, totalPages: 1 }); fixture.componentInstance.refreshQuotes(); http.expectOne('/api/acoes/1/atualizar-cotacao').flush({}); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items: [position(1, 'PETR4', 'Corretora A', 2, 'BRL')], page: 0, size: 20, totalElements: 1, totalPages: 1 }); });
  it('apenas relê posições quando a carteira está vazia', () => { start(); fixture.componentInstance.refreshQuotes(); http.expectNone(request => request.method === 'PUT'); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }); });
});

function unavailable(currency: string): any { return { availability: 'UNAVAILABLE', value: null, currency, reason: 'QUOTE_UNAVAILABLE' }; }
function position(id: number, ticker: string, brokerName: string, quantity: number, currency: 'BRL' | 'USD'): any {
  const money = (value: number) => ({ availability: 'AVAILABLE', value, currency, reason: null });
  return { positionId: id, assetId: id, ticker, assetName: ticker === 'PETR4' ? 'Petróleo Brasileiro S.A.' : 'Apple Inc.', market: currency === 'BRL' ? 'BRASIL' : 'AMERICANO', brokerId: id, brokerName, quantity, nativeCurrency: currency, averagePrice: money(10.5), cost: money(21), currentQuote: money(12), marketValue: money(24), unrealizedResult: money(3), unrealizedResultPercentage: { availability: 'AVAILABLE', value: 14.2857, reason: null }, realizedResult: money(4), quoteProvenance: { availability: 'AVAILABLE', sourceType: 'STUB', provider: 'Provedor sintético', referenceAt: '2026-09-06T15:00:00Z', fetchedAt: '2026-09-06T15:01:00Z', referenceKind: 'MARKET', currency, reason: null } };
}
