import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { CarteiraComponent } from './carteira';

describe('CarteiraComponent', () => {
  let fixture: ComponentFixture<CarteiraComponent>; let http: HttpTestingController;
  beforeEach(async () => { await TestBed.configureTestingModule({ imports: [CarteiraComponent], providers: [provideRouter([]), provideHttpClient(), provideHttpClientTesting()] }).compileComponents(); fixture = TestBed.createComponent(CarteiraComponent); http = TestBed.inject(HttpTestingController); });
  afterEach(() => http.verify());
  function start(items: any[] = []): void { fixture.detectChanges(); http.expectOne('/api/corretoras').flush([]); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items, page: 0, size: 20, totalElements: items.length, totalPages: items.length ? 1 : 0 }); }
  it('reserva loading e apresenta vazio confirmado', () => { fixture.detectChanges(); http.expectOne('/api/corretoras').flush([]); expect(fixture.nativeElement.querySelector('[aria-busy="true"]')).toBeTruthy(); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Nenhuma posição encontrada'); });
  it('apresenta erro completo com repetição de leitura', () => { fixture.detectChanges(); http.expectOne('/api/corretoras').flush([]); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({ message: 'Carteira indisponível' }, { status: 503, statusText: 'Unavailable' }); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="alert"]')).toBeTruthy(); expect(fixture.nativeElement.querySelector('app-error-summary button')).toBeTruthy(); });
  it('envia filtros server-side e preserva busca/ordenação na página', () => { start([position(1, 'PETR4', 'Corretora B', 2), position(2, 'PETR4', 'Corretora A', 5)]); const component = fixture.componentInstance; component.filters.setValue({ search: 'corretora', market: 'BRASIL', brokerId: 7, sort: 'broker' }); component.applyFilters(); const request = http.expectOne(value => value.url === '/api/carteira/posicoes/detalhadas'); expect(request.request.params.get('market')).toBe('BRASIL'); expect(request.request.params.get('brokerId')).toBe('7'); request.flush({ items: [position(1, 'PETR4', 'Corretora B', 2), position(2, 'PETR4', 'Corretora A', 5)], page: 0, size: 20, totalElements: 2, totalPages: 1 }); expect(component.visiblePositions.map(item => item.brokerName)).toEqual(['Corretora A', 'Corretora B']); });
  it('mantém mesmo ticker separado por corretora', () => { start([position(1, 'PETR4', 'A', 2), position(2, 'PETR4', 'B', 3)]); expect(fixture.componentInstance.visiblePositions).toHaveLength(2); expect(new Set(fixture.componentInstance.visiblePositions.map(item => item.positionId)).size).toBe(2); });
  it('preserva posição e marca stale em falha posterior', () => { start([position(1, 'PETR4', 'A', 2)]); fixture.componentInstance.load(); http.expectOne(request => request.url === '/api/carteira/posicoes/detalhadas').flush({}, { status: 503, statusText: 'Unavailable' }); expect(fixture.componentInstance.facade.state().status).toBe('stale'); expect(fixture.componentInstance.visiblePositions).toHaveLength(1); });
  it('exibe indisponibilidade individual sem zero', () => { const item = position(1, 'AAPL', 'A', 1); item.currentQuote = { availability: 'UNAVAILABLE', value: null, currency: 'USD', reason: 'QUOTE_UNAVAILABLE' }; item.marketValue = { availability: 'UNAVAILABLE', value: null, currency: 'USD', reason: 'QUOTE_UNAVAILABLE' }; start([item]); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Indisponível'); });
  it('recolhe filtros sem perder valores e anuncia quantos estão ativos', () => { start(); const component = fixture.componentInstance; component.filters.patchValue({ search: 'AAPL', market: 'AMERICANO' }); expect(component.activeFilterCount).toBe(2); component.toggleFilters(); fixture.detectChanges(); expect(component.filtersExpanded).toBe(true); expect((fixture.nativeElement as HTMLElement).querySelector('.filter-toggle')?.getAttribute('aria-expanded')).toBe('true'); expect(component.filters.controls.search.value).toBe('AAPL'); });
});
function position(id: number, ticker: string, brokerName: string, quantity: number): any { const money = { availability: 'AVAILABLE', value: 10, currency: 'BRL', reason: null }; return { positionId: id, assetId: id, ticker, market: 'BRASIL', brokerId: id, brokerName, quantity, nativeCurrency: 'BRL', averagePrice: money, cost: money, currentQuote: money, marketValue: money, unrealizedResult: money, quoteProvenance: { availability: 'AVAILABLE', sourceType: 'STUB', provider: 'Provedor sintético', referenceAt: '2026-09-06T15:00:00Z', fetchedAt: '2026-09-06T15:01:00Z', referenceKind: 'MARKET', currency: 'BRL', reason: null } }; }
