import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { Subject } from 'rxjs';
import { vi } from 'vitest';
import { AcaoComponent } from './acao';

describe('AcaoComponent', () => {
  let fixture: ComponentFixture<AcaoComponent>; let http: HttpTestingController;
  beforeEach(async () => { await TestBed.configureTestingModule({ imports: [AcaoComponent], providers: [provideRouter([]), provideHttpClient(), provideHttpClientTesting()] }).compileComponents(); fixture = TestBed.createComponent(AcaoComponent); http = TestBed.inject(HttpTestingController); });
  afterEach(() => { vi.useRealTimers(); http.verify({ ignoreCancelled: true }); });
  it('renders loading and empty state', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Nenhum ativo cadastrado'); });
  it('shows waiting market before a ticker is provided', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Aguardando ticker'); });
  it('renders the catalog loading state before the initial response', () => { fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Carregando catálogo de ações'); http.expectOne('/api/acoes').flush([]); });
  it('normalizes ticker and detects the Brazilian market', () => { const component = fixture.componentInstance; component.form.controls.ticker.setValue('petr4'); component.normalizarEIdentificarMercado(); expect(component.form.controls.ticker.value).toBe('PETR4'); expect(component.form.controls.mercado.value).toBe('BRASIL'); });
  it('consults a preview before saving', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); const component = fixture.componentInstance; component.form.setValue({ ticker: 'aapl', mercado: 'AMERICANO' }); component.consultarAtivo(); const preview = http.expectOne(item => item.url === '/api/acoes/consulta'); expect(preview.request.params.get('ticker')).toBe('AAPL'); preview.flush({ ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100, dataHoraCotacao: '2026-09-10T12:00:00Z' }); expect(component.previa?.nomeEmpresa).toBe('Apple Inc.'); });
  it('uses professional legacy copy without deprecated terms', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([{ id: 1, ticker: 'AAPL', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 20 }]); fixture.detectChanges(); const text = fixture.nativeElement.textContent as string; expect(text).toContain('Atualização necessária'); expect(text).toContain('Atualize a cotação para completar os dados da fonte.'); expect(text).not.toMatch(/freshness|contrato legado|origem não informada|\?/i); });
  it('aborts the real Angular HTTP request on cancel', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); const component = fixture.componentInstance; component.form.setValue({ ticker: 'AAPL', mercado: 'AMERICANO' }); component.consultarAtivo(); const request = http.expectOne(item => item.url === '/api/acoes/consulta'); component.cancelarConsulta(); expect(request.cancelled).toBe(true); expect(component.consultando).toBe(false); });
  it('times out after 12 seconds and updates the rendered retry state', async () => { vi.useFakeTimers(); fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); const response = new Subject<any>(); vi.spyOn((fixture.componentInstance as any).service, 'consultar').mockReturnValue(response); const component = fixture.componentInstance; component.form.setValue({ ticker: 'AAPL', mercado: 'AMERICANO' }); component.consultarAtivo(); await vi.advanceTimersByTimeAsync(12001); await fixture.whenStable(); const text = fixture.nativeElement.textContent as string; expect(text).not.toContain('Consultando…'); expect(text).toContain('A consulta excedeu 12 segundos'); const buttons = Array.from((fixture.nativeElement as HTMLElement).querySelectorAll('button')); expect(buttons.filter(button => button.textContent?.includes('Tentar novamente'))).toHaveLength(1); response.next({ ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100 }); expect(component.previa).toBeNull(); });
  it('cancel clears preview and ignores a late Subject response', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); const response = new Subject<any>(); vi.spyOn((fixture.componentInstance as any).service, 'consultar').mockReturnValue(response); const component = fixture.componentInstance; component.previa = { ticker: 'AAPL', mercado: 'AMERICANO' }; component.form.setValue({ ticker: 'AAPL', mercado: 'AMERICANO' }); component.consultarAtivo(); component.cancelarConsulta(); expect(component.consultando).toBe(false); expect(component.previa).toBeNull(); response.next({ ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100 }); expect(component.previa).toBeNull(); });
  it('shows one functional retry action after a failed consultation', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); const component = fixture.componentInstance; component.form.setValue({ ticker: 'AAPL', mercado: 'AMERICANO' }); component.consultarAtivo(); http.expectOne(item => item.url === '/api/acoes/consulta').flush({ message: 'Indisponível' }, { status: 503, statusText: 'Unavailable' }); fixture.detectChanges(); const nativeElement = fixture.nativeElement as HTMLElement; const buttons = Array.from(nativeElement.querySelectorAll('button')); const retry = buttons.filter(button => button.textContent?.includes('Tentar novamente')); expect(retry).toHaveLength(1); });
  it('renders a duplicate save error and clears Salvar without another interaction', async () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); const component = fixture.componentInstance; component.form.setValue({ ticker: 'AAPL', mercado: 'AMERICANO' }); component.previa = { ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100 }; component.adicionarAcao(); http.expectOne('/api/acoes').flush({ code: 'DUPLICATE_TICKER', message: 'Este ticker já está cadastrado neste mercado.' }, { status: 409, statusText: 'Conflict' }); await fixture.whenStable(); const text = fixture.nativeElement.textContent as string; expect(text).toContain('Este ticker já está cadastrado neste mercado.'); expect(text).not.toContain('Salvando…'); });
  it('renders an update error only on its asset row without form interaction', async () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([{ id: 9, ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100 }]); const component = fixture.componentInstance; component.atualizarPreco(9); http.expectOne('/api/acoes/9/atualizar-cotacao').flush({ message: 'Fonte temporariamente indisponível.' }, { status: 503, statusText: 'Unavailable' }); await fixture.whenStable(); const nativeElement = fixture.nativeElement as HTMLElement; expect(nativeElement.textContent).toContain('Fonte temporariamente indisponível.'); expect(nativeElement.querySelector('.message-slot')?.textContent).not.toContain('Fonte temporariamente indisponível.'); expect(nativeElement.textContent).not.toContain('Atualizando…'); });
  it('times out saving and updating in the rendered DOM', async () => { vi.useFakeTimers(); fixture.detectChanges(); http.expectOne('/api/acoes').flush([{ id: 9, ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100 }]); const component = fixture.componentInstance; const save = new Subject<any>(); const update = new Subject<any>(); vi.spyOn((component as any).service, 'salvar').mockReturnValue(save); vi.spyOn((component as any).service, 'atualizarCotacao').mockReturnValue(update); component.form.setValue({ ticker: 'AAPL', mercado: 'AMERICANO' }); component.previa = { ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100 }; component.adicionarAcao(); await vi.advanceTimersByTimeAsync(12001); await fixture.whenStable(); expect(fixture.nativeElement.textContent).toContain('O cadastro excedeu 12 segundos'); expect(fixture.nativeElement.textContent).not.toContain('Salvando…'); component.atualizarPreco(9); await vi.advanceTimersByTimeAsync(12001); await fixture.whenStable(); expect(fixture.nativeElement.textContent).toContain('A atualização excedeu 12 segundos'); expect(fixture.nativeElement.textContent).not.toContain('Atualizando…'); });
  it('uses one fixed ticker feedback slot that replaces help with validation', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([]); fixture.detectChanges(); const nativeElement = fixture.nativeElement as HTMLElement; const before = nativeElement.querySelectorAll('#asset-ticker-feedback').length; fixture.componentInstance.consultarAtivo(); fixture.detectChanges(); const feedback = nativeElement.querySelector('#asset-ticker-feedback') as HTMLElement; expect(before).toBe(1); expect(nativeElement.querySelectorAll('#asset-ticker-feedback')).toHaveLength(1); expect(feedback.textContent).toContain('Informe um ticker válido'); expect(feedback.textContent).not.toContain('Ex.: PETR4'); expect(nativeElement.querySelector('#asset-ticker')?.getAttribute('aria-describedby')).toBe('asset-ticker-feedback'); });
  it('compacts the source column to provider badges only', () => { fixture.detectChanges(); http.expectOne('/api/acoes').flush([{ id: 1, ticker: 'PETR4', nomeEmpresa: 'Petrobras', mercado: 'BRASIL', moeda: 'BRL', cotacaoAtual: 20, quoteProvider: 'BRAPI', quoteSourceType: 'MARKET_DATA_PROVIDER' }, { id: 2, ticker: 'AAPL', nomeEmpresa: 'Apple Inc.', mercado: 'AMERICANO', moeda: 'USD', cotacaoAtual: 100, quoteProvider: 'Twelve Data', quoteSourceType: 'MARKET_DATA_PROVIDER' }]); fixture.detectChanges(); const text = fixture.nativeElement.textContent as string; expect(text).toContain('Fonte'); expect(text).toContain('BRAPI'); expect(text).toContain('Twelve Data'); expect(text).not.toContain('MARKET_DATA_PROVIDER'); expect(text).not.toContain('Atualização disponível conforme a fonte da cotação'); });
});
