import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { DashboardComponent } from './dashboard';

describe('DashboardComponent', () => {
  let fixture: ComponentFixture<DashboardComponent>; let http: HttpTestingController;
  beforeEach(async () => { await TestBed.configureTestingModule({ imports: [DashboardComponent], providers: [provideRouter([]), provideHttpClient(), provideHttpClientTesting()] }).compileComponents(); fixture = TestBed.createComponent(DashboardComponent); http = TestBed.inject(HttpTestingController); });
  afterEach(() => http.verify());
  it('reserva loading e apresenta erro completo com repetição', () => { fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[aria-busy="true"]')).toBeTruthy(); http.expectOne('/api/carteira/dashboard').flush({ message: 'Dashboard indisponível' }, { status: 503, statusText: 'Unavailable' }); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="alert"]')).toBeTruthy(); expect(fixture.nativeElement.querySelector('app-error-summary button')).toBeTruthy(); });
  it('consome somente o read model do dashboard e distingue zero confirmado', () => { fixture.detectChanges(); const request = http.expectOne('/api/carteira/dashboard'); expect(request.request.method).toBe('GET'); request.flush(dashboardFixture()); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Posições ativas'); expect(fixture.nativeElement.textContent).toContain('R$ 0,00'); http.expectNone('/api/carteira/posicoes'); http.expectNone('/api/carteira/saldo-total'); });
  it('não apresenta ausência esperada de câmbio na carteira vazia como falha parcial', () => { fixture.detectChanges(); http.expectOne('/api/carteira/dashboard').flush(dashboardFixture()); fixture.detectChanges(); expect(fixture.nativeElement.textContent).not.toContain('Dados parciais'); expect(fixture.nativeElement.textContent).toContain('Nenhuma posição ativa'); });
  it('mostra métrica indisponível e dados parciais sem zero substituto', () => { fixture.detectChanges(); const payload = dashboardFixture(); payload.positionCount = 1; payload.positions = [positionFixture()]; payload.patrimony = { availability: 'UNAVAILABLE', value: null, currency: 'BRL', reason: 'EXCHANGE_RATE_UNAVAILABLE' }; http.expectOne('/api/carteira/dashboard').flush(payload); fixture.detectChanges(); const text = fixture.nativeElement.textContent as string; expect(text).toContain('Dados parciais'); expect(text).toContain('Indisponível'); expect(text).not.toContain('Patrimônio estimadoR$ 0,00'); });
  it('preserva dados anteriores como stale após falha de atualização', () => { fixture.detectChanges(); http.expectOne('/api/carteira/dashboard').flush({ ...dashboardFixture(), positionCount: 1, positions: [positionFixture()] }); fixture.componentInstance.refresh(); http.expectOne('/api/carteira/dashboard').flush({}, { status: 503, statusText: 'Unavailable' }); expect(fixture.componentInstance.facade.state().status).toBe('stale'); expect(fixture.componentInstance.data?.positionCount).toBe(1); });
  it('não contém formulário de operação', () => { fixture.detectChanges(); http.expectOne('/api/carteira/dashboard').flush(dashboardFixture()); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('form')).toBeNull(); expect(fixture.nativeElement.querySelector('a[href="/operacoes"]')).toBeTruthy(); });
});
function dashboardFixture(): any { const money = { availability: 'AVAILABLE', value: 0, currency: 'BRL', reason: null }; return { asOf: '2026-09-06T15:00:00Z', presentationCurrency: 'BRL', positionCount: 0, patrimony: money, cost: money, unrealizedResult: money, unrealizedResultPercentage: { availability: 'UNAVAILABLE', value: null, reason: 'EMPTY_PORTFOLIO' }, positions: [], recentMovements: [], quoteSources: [], exchangeSource: { availability: 'UNAVAILABLE', baseCurrency: 'USD', quoteCurrency: 'BRL', rate: null, sourceType: null, provider: null, referenceAt: null, fetchedAt: null, referenceKind: null, reason: 'NOT_REQUIRED' } }; }
function positionFixture(): any { const money = { availability: 'AVAILABLE', value: 10, currency: 'BRL', reason: null }; return { positionId: 1, assetId: 1, ticker: 'PETR4', market: 'BRASIL', brokerId: 1, brokerName: 'Corretora sintética', quantity: 1, nativeCurrency: 'BRL', averagePrice: money, cost: money, currentQuote: money, marketValue: money, unrealizedResult: money, quoteProvenance: { availability: 'AVAILABLE', sourceType: 'STUB', provider: 'Provedor sintético', referenceAt: '2026-09-06T15:00:00Z', fetchedAt: '2026-09-06T15:01:00Z', referenceKind: 'MARKET', currency: 'BRL', reason: null } }; }
